- name: variables
  hosts: local
  connection: local
  vars:
    DAY: MONDAY
    DATE: "21ST JULY"
    TIME: 8:30Am
  tasks:
  - name: print the variable
    ansible.builtin.debug:
      msg: "Today is {{ DAY }} , Date is {{ DATE }}, Time is {{ TIME }}"