- name: variables
  hosts: local
  connection: local
  vars: #play level variables, global variables 
    DAY: MONDAY
    DATE: "21ST JULY"
    TIME: 8:30Am
  tasks:
  - name: print the variables
    vars: #task level variables, accessable within the task . task variables can override play level variables. Local variables
     DAY: FRIDAY
     ansible.builtin.debug:
      msg: "Today is {{ DAY }} , Date is {{ DATE }}, Time is {{ TIME }}"


  - name: print the variables1
    ansible.builtin.debug:
      msg: "Today is {{ DAY }} , Date is {{ DATE }}, Time is {{ TIME }}"